### ISSUE TITLE
callRegions output avg.posterior as array type

### ISSUE THREAD

**Issue by JohnMCMa** [matthiasheinig/histoneHMM#5]
Hi,

`callRegions` calculates the average posterior by `tapply`, i.e. `reduced.posterior = apply(elementMetadata(called.granges)[,posterior.col], called2reduced[,2], mean, na.rm=T)`. Since the output of `tapply` is an `array` type by default, the `avg.posterior` field of `reduced.granges` is also of this type.

This turns out to cause breaking errors when using `makeGffAttributes` on `reduced.granges`, as `as.data.frame` in some versions of S4Vectors doesn't seem to properly parse a `DataFrame` with a field of `array` type. This in turns breaks `GR2gff`, and, thus, also breaks `histoneHMM_call_regions.R`.

On our side, one way to fix it is to coerce `reduced.posterior` (and, similarly, `reduced.expression`) to `numeric` before putting them in `mcols (reduced.granges)`.

**Comment by matthiasheinig** [comment]
Thanks, I added this to the callRegions function, could you try if it works?

**Comment by JohnMCMa** [comment]
Hi @matthiasheinig : Thanks for the quick response; I will look at it.

**Comment by JohnMCMa** [comment]
Hi @matthiasheinig ,

I installed and ran your code. There aren't any of the issue I raised, but I noticed these warnings at the end of `histoneHMM_differential.R`:

```
Warning messages:
[Directory already exists warning skipped]
2: In x - m :
  Recycling array of length 1 in vector-array arithmetic is deprecated.
  Use c() or as.vector() instead.

3: In x - m :
  Recycling array of length 1 in vector-array arithmetic is deprecated.
  Use c() or as.vector() instead.

4: In x - m :
  Recycling array of length 1 in vector-array arithmetic is deprecated.
  Use c() or as.vector() instead.

5: In x - m :
  Recycling array of length 1 in vector-array arithmetic is deprecated.
  Use c() or as.vector() instead.
```

**Comment by matthiasheinig** [comment]
Thanks for running! I will look into this..
