### ISSUE TITLE
make new release for conda

### ISSUE THREAD

**Issue by steffenheyne** [matthiasheinig/histoneHMM#7]
The current git version seems to solve some problems/errors we get with histoneHMM.

Please make a new release so that we can get this also as a new conda version!
Thank you!

**Comment by dpryan79** [comment]
Expanding upon, this, please tag your releases!

**Comment by matthiasheinig** [comment]
Sorry for being very slow.. I made a new release and tagged it:

https://github.com/matthiasheinig/histoneHMM/releases/tag/v1.8

**Comment by dpryan79** [comment]
Thanks @matthiasheinig!
