### ISSUE TITLE
question about input controls

### ISSUE THREAD

**Issue by kmattioli** [matthiasheinig/histoneHMM#9]
Hello,

Thank you for your work on histoneHMM! I have been using it to analyze some H3K27me3 ChIP-seq data. I just was wondering if you could clarify for me what the best way to include input controls per sample is, in your opinion? Would it be advisable to call differential peaks between IP & input first, and then use the significant peaks as input into other differential analyses? Or would you simply subtract any peaks that show up in the input as well? (Or something else I missed?)

**Comment by matthiasheinig** [comment]
Hi Kaia,
are you doing a differential analysis between conditions or are you interested to call H3K27me3 domains in one sample only?
In our paper (https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-015-0491-6) we have evaluated both applications without using input controls and showed better (especially for single sample analysis) or comparable performance with tools that use input control.
Best,
Matthias

**Comment by kmattioli** [comment]
Hi Matthias,

Sorry for not being clear! I am interested in doing a differential analysis between conditions (drug treatments), but for each condition I have the IP sample of interest and the input control. From your response (and after reading the paper, thanks!), it sounds like histoneHMM does not use information from the input control to do any region calling, correct? I am just wondering whether I should be using the input control data at all in some way when performing this analysis, but it sounds like in your work you don't see that using input control, at least for broad domains, makes much of a difference when benchmarking.

-kaia

**Comment by matthiasheinig** [comment]
Hi Kaia,

yes exactly methods that use input are not performing better than our method without input. Especially in the differential analysis this is also quite intuitive I think: when the input remains more or less constant when looking at the ratio of (condition1/input) / (condition2/input) the input cancels out..

Best,
Matthias
